### ISSUE TITLE
I have this problem with some asshole NPC called "sun" who steals my shit

### ISSUE THREAD

**Issue by Dreamms** [ckaraviotis/solipsists-minecraft#2]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 23/09/15 19:45
Description: Updating screen events

java.lang.ClassCastException: null not an ItemStack, ItemStack[] or List<ItemStack?
    at codechicken.nei.NEIServerUtils.extractRecipeItems(NEIServerUtils.java:344)
    at codechicken.nei.PositionedStack.<init>(PositionedStack.java:27)
    at codechicken.nei.PositionedStack.<init>(PositionedStack.java:39)
    at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:33)
    at net.machinemuse.numina.nei.JSONRecipeHandler.JSONShapedRecipe(JSONRecipeHandler.java:192)
    at net.machinemuse.numina.nei.JSONRecipeHandler.loadUsageRecipes(JSONRecipeHandler.java:81)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
    at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
    at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at codechicken.nei.NEIServerUtils.extractRecipeItems(NEIServerUtils.java:344)
    at codechicken.nei.PositionedStack.<init>(PositionedStack.java:27)
    at codechicken.nei.PositionedStack.<init>(PositionedStack.java:39)
    at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:33)
    at net.machinemuse.numina.nei.JSONRecipeHandler.JSONShapedRecipe(JSONRecipeHandler.java:192)
    at net.machinemuse.numina.nei.JSONRecipeHandler.loadUsageRecipes(JSONRecipeHandler.java:81)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
    at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
    at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['jamiusceaser'/3745, l='MpServer', x=-855.37, y=132.55, z=1113.79]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 17167955 game time, 17776094 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 108 total; [EntityCow['Cow'/295805, l='MpServer', x=-786.44, y=69.00, z=1113.72], EntityCow['Cow'/295804, l='MpServer', x=-788.16, y=70.00, z=1111.97], EntitySkeleton['Skeleton'/298920, l='MpServer', x=-872.50, y=74.00, z=1075.50], EntityCow['Cow'/295803, l='MpServer', x=-791.84, y=73.00, z=1092.97], EntitySkeleton['Skeleton'/300554, l='MpServer', x=-824.82, y=73.00, z=1055.42], EntityBat['Bat'/297421, l='MpServer', x=-890.53, y=27.20, z=1100.94], EntityPig['Pig'/294726, l='MpServer', x=-830.50, y=79.00, z=1122.31], EntityBat['Bat'/297420, l='MpServer', x=-885.40, y=21.92, z=1083.25], EntityCreeper['Creeper'/300571, l='MpServer', x=-933.56, y=78.59, z=1105.48], EntityCreeper['Creeper'/300574, l='MpServer', x=-849.50, y=27.00, z=1064.50], EntitySkeleton['Skeleton'/296720, l='MpServer', x=-898.50, y=24.00, z=1086.50], EntitySheep['Sheep'/292854, l='MpServer', x=-851.66, y=76.00, z=1107.84], EntitySheep['Sheep'/292853, l='MpServer', x=-853.03, y=71.00, z=1061.97], EntitySpider['Spider'/297932, l='MpServer', x=-929.50, y=77.00, z=1115.50], EntityBat['Bat'/298401, l='MpServer', x=-855.75, y=42.00, z=1110.56], EntityBat['Bat'/297454, l='MpServer', x=-888.53, y=45.25, z=1096.05], EntityBat['Bat'/297456, l='MpServer', x=-885.60, y=41.55, z=1111.29], EntityCreeper['Creeper'/296704, l='MpServer', x=-888.50, y=20.00, z=1115.50], EntitySkeleton['Skeleton'/6136542, l='MpServer', x=26.56, y=-27.47, z=8.45], EntitySkeleton['Skeleton'/293219, l='MpServer', x=-915.50, y=36.00, z=1070.50], EntityOtherPlayerMP['chanza'/7223, l='MpServer', x=-335.77, y=235.00, z=966.81], EntityCow['Cow'/295191, l='MpServer', x=-804.63, y=71.00, z=1139.41], EntityWitch['Witch'/298983, l='MpServer', x=-888.50, y=46.00, z=1143.50], EntityWitch['Witch'/298982, l='MpServer', x=-889.50, y=46.00, z=1142.50], EntitySheep['Sheep'/294687, l='MpServer', x=-846.03, y=73.00, z=1067.03], EntityHangGlider['entity.OpenBlocks.Hang Glider.name'/297914, l='MpServer', x=-857.22, y=130.22, z=1112.47], EntityZombie['Zombie'/6137861, l='MpServer', x=45.30, y=-13.62, z=41.43], EntityBat['Bat'/298995, l='MpServer', x=-924.28, y=32.67, z=1095.75], EntityCreeper['Creeper'/295223, l='MpServer', x=-920.50, y=31.00, z=1117.50], EntityCow['Cow'/295696, l='MpServer', x=-797.91, y=67.00, z=1120.19], EntityCow['Cow'/295695, l='MpServer', x=-801.63, y=67.00, z=1131.39], EntityBat['Bat'/300124, l='MpServer', x=-894.75, y=23.00, z=1150.75], EntityEnderman['Enderman'/297838, l='MpServer', x=-854.34, y=77.00, z=1104.78], EntityCreeper['Creeper'/300205, l='MpServer', x=-820.50, y=39.00, z=1109.50], EntityCreeper['Creeper'/295927, l='MpServer', x=-915.50, y=64.00, z=1109.50], EntityCartChest['entity.MinecartChest.name'/280122, l='MpServer', x=-734.50, y=16.34, z=1163.50], EntityZombie['Zombie'/299741, l='MpServer', x=-781.50, y=71.00, z=1134.50], EntityClientPlayerMP['jamiusceaser'/3745, l='MpServer', x=-855.37, y=132.55, z=1113.79], EntityCreeper['Creeper'/300209, l='MpServer', x=-913.50, y=28.00, z=1155.50], EntityCreeper['Creeper'/296381, l='MpServer', x=-856.50, y=66.00, z=1033.50], EntitySkeleton['Skeleton'/296370, l='MpServer', x=-890.50, y=67.00, z=1033.50], EntityZombie['Zombie'/297336, l='MpServer', x=-854.00, y=42.00, z=1110.56], EntityCreeper['Creeper'/300191, l='MpServer', x=-851.50, y=74.00, z=1123.50], EntityZombie['Zombie'/297339, l='MpServer', x=-858.69, y=43.00, z=1110.28], EntitySpider['Spider'/297338, l='MpServer', x=-856.97, y=43.00, z=1111.69], EntityZombie['Zombie'/297341, l='MpServer', x=-858.50, y=43.00, z=1115.50], EntityZombie['Zombie'/297340, l='MpServer', x=-858.50, y=43.00, z=1112.50], EntityCreeper['Creeper'/294907, l='MpServer', x=-932.50, y=64.00, z=1121.50], EntityZombie['Zombie'/297335, l='MpServer', x=-854.50, y=43.00, z=1114.50], EntityCreeper['Creeper'/294909, l='MpServer', x=-930.50, y=64.00, z=1123.50], EntityZombie['Zombie'/297334, l='MpServer', x=-886.50, y=70.00, z=1063.50], EntitySkeleton['Skeleton'/298304, l='MpServer', x=-912.53, y=67.00, z=1052.16], EntitySkeleton['Skeleton'/298305, l='MpServer', x=-919.50, y=69.00, z=1050.50], EntityBat['Bat'/296414, l='MpServer', x=-915.41, y=33.62, z=1126.96], EntitySheep['Sheep'/294796, l='MpServer', x=-829.75, y=78.00, z=1093.50], EntityPig['Pig'/294797, l='MpServer', x=-817.13, y=77.00, z=1095.97], EntityPig['Pig'/294798, l='MpServer', x=-832.56, y=77.00, z=1103.69], EntityCreeper['Creeper'/295866, l='MpServer', x=-935.50, y=68.00, z=1132.50], EntityPig['Pig'/294795, l='MpServer', x=-828.47, y=78.00, z=1102.66], EntityCow['Cow'/291655, l='MpServer', x=-924.50, y=71.00, z=1036.47], EntityCreeper['Creeper'/296384, l='MpServer', x=-854.50, y=66.00, z=1033.50], EntityBat['Bat'/299852, l='MpServer', x=-829.82, y=19.56, z=1127.21], EntityBat['Bat'/300813, l='MpServer', x=-859.70, y=38.43, z=1168.31], EntityBat['Bat'/297705, l='MpServer', x=-875.23, y=31.16, z=1078.61], EntitySkeleton['Skeleton'/299884, l='MpServer', x=-868.47, y=67.00, z=1138.88], EntityCreeper['Creeper'/299883, l='MpServer', x=-873.50, y=67.00, z=1142.50], EntityItem['item.tile.coral1.pinkcoral'/292965, l='MpServer', x=-872.28, y=55.13, z=1168.59], EntityCreeper['Creeper'/299782, l='MpServer', x=-877.50, y=67.00, z=1148.50], EntityZombie['Zombie'/297142, l='MpServer', x=-924.50, y=38.00, z=1101.50], EntityCreeper['Creeper'/300917, l='MpServer', x=-796.50, y=72.00, z=1087.50], EntitySpider['Spider'/300919, l='MpServer', x=-794.10, y=72.00, z=1088.50], EntitySpider['Spider'/298712, l='MpServer', x=-824.50, y=69.37, z=1044.99], EntityZombie['Zombie'/300913, l='MpServer', x=-796.50, y=72.00, z=1086.50], EntitySheep['Sheep'/292513, l='MpServer', x=-876.75, y=69.00, z=1054.13], EntityZombie['Zombie'/300915, l='MpServer', x=-795.69, y=72.00, z=1088.50], EntitySkeleton['Skeleton'/300927, l='MpServer', x=-909.50, y=74.00, z=1095.50], EntityCreeper['Creeper'/298704, l='MpServer', x=-862.31, y=71.00, z=1109.94], EntityZombie['Zombie'/6137801, l='MpServer', x=42.18, y=-16.12, z=-44.30], EntityZombie['Zombie'/298222, l='MpServer', x=-870.50, y=69.00, z=1053.50], EntityZombie['Zombie'/298221, l='MpServer', x=-870.72, y=71.00, z=1062.09], EntityCreeper['Creeper'/300945, l='MpServer', x=-802.50, y=72.00, z=1078.50], EntityZombie['Zombie'/300944, l='MpServer', x=-795.50, y=72.00, z=1085.50], EntitySheep['Sheep'/294620, l='MpServer', x=-839.13, y=71.00, z=1114.19], EntityZombie['Zombie'/300460, l='MpServer', x=-894.50, y=20.00, z=1081.50], EntitySkeleton['Skeleton'/300462, l='MpServer', x=-881.50, y=67.00, z=1099.50], EntitySkeleton['Skeleton'/296632, l='MpServer', x=-920.50, y=69.00, z=1035.50], EntityWitch['Witch'/300937, l='MpServer', x=-799.50, y=72.00, z=1082.50], EntityZombie['Zombie'/300942, l='MpServer', x=-800.50, y=72.00, z=1081.50], EntitySkeleton['Skeleton'/6136684, l='MpServer', x=-5.61, y=-13.62, z=59.60], EntityWitch['Witch'/300940, l='MpServer', x=-798.50, y=72.00, z=1076.50], EntityCreeper['Creeper'/300458, l='MpServer', x=-932.50, y=68.00, z=1075.50], EntityZombie['Zombie'/300941, l='MpServer', x=-799.50, y=72.00, z=1080.50], EntityCow['Cow'/296626, l='MpServer', x=-778.81, y=69.00, z=1114.19], EntityCow['Cow'/296627, l='MpServer', x=-781.16, y=71.00, z=1126.03], EntityCow['Cow'/296625, l='MpServer', x=-779.78, y=68.00, z=1116.72], EntityBat['Bat'/295674, l='MpServer', x=-902.41, y=36.00, z=1062.97], EntityWitch['Witch'/300935, l='MpServer', x=-834.50, y=73.00, z=1169.50], EntityItem['item.item.dyePowder.black'/291919, l='MpServer', x=-907.44, y=55.13, z=1139.06], EntitySheep['Sheep'/291918, l='MpServer', x=-899.13, y=69.00, z=1058.34], EntityOtherPlayerMP['SunOfaBeach'/8517, l='MpServer', x=-570.53, y=107.28, z=1039.35], EntityZombie['Zombie'/299481, l='MpServer', x=-844.50, y=34.00, z=1132.50], EntityOtherPlayerMP['SunOfaBeach'/8517, l='MpServer', x=-577.15, y=107.78, z=1040.48], EntityCreeper['Creeper'/296700, l='MpServer', x=-886.50, y=20.00, z=1114.50], EntityCreeper['Creeper'/296701, l='MpServer', x=-883.56, y=21.00, z=1114.03], EntityBat['Bat'/298059, l='MpServer', x=-890.91, y=58.00, z=1052.38], EntityBat['Bat'/297004, l='MpServer', x=-919.28, y=35.26, z=1112.25], EntityCreeper['Creeper'/295572, l='MpServer', x=-865.25, y=70.00, z=1050.94], EntitySheep['Sheep'/295096, l='MpServer', x=-816.25, y=69.00, z=1111.84]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2613508448 bytes (2492 MB) / 3848273920 bytes (3670 MB) up to 4294967296 bytes (4096 MB)
    JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 78 mods loaded, 78 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](modpack.jar) 
    UCHIJA  Forge{10.13.4.1448} [Minecraft Forge](modpack.jar) 
    UCHIJA  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJA  CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJA  MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJA  OpenComputers|Core{1.5.17.33} [OpenComputers (Core)](minecraft.jar) 
    UCHIJA  VeinMiner_coremod{0.27.1_build.unknown} [Core mod](minecraft.jar) 
    UCHIJA  OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJA  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJA  debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJA  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJA  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJA  ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJA  BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHIJA  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
    UCHIJA  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-13.jar) 
    UCHIJA  Botania{r1.7-221} [Botania](Botania r1.7-221.jar) 
    UCHIJA  ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJA  Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJA  chunkgen{1.7.10-1.2.2} [ChunkGen](chunkgen-1.7.10-1.2.3.jar) 
    UCHIJA  EnderStorage{1.4.7.33} [EnderStorage](EnderStorage-1.7.10-1.4.7.33-universal.jar) 
    UCHIJA  MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  OpenComputers{1.5.17.33} [OpenComputers](OpenComputers-MC1.7.10-1.5.17.33-universal.jar) 
    UCHIJA  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJA  CompactMachines{1.7.10-1.20} [Compact Machines](compactmachines-1.7.10-1.20.jar) 
    UCHIJA  Dynmap{2.1-104} [Dynmap](Dynmap-2.1-forge-1.7.10.jar) 
    UCHIJA  EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJA  ProjectE{1.7.10-PE1.8.0} [ProjectE](ProjectE-1.7.10-PE1.8.0.jar) 
    UCHIJA  equivalentenergistics{0.6} [Equivalent Energistics](EquivalentEnergistics - 0.6 - 1.7.10.jar) 
    UCHIJA  extracells{2.2.73} [Extra Cells 2](ExtraCells-1.7.10-2.2.73b129.jar) 
    UCHIJA  ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCHIJA  Forestry{3.6.3.20} [Forestry for Minecraft](forestry_1.7.10-3.6.3.20.jar) 
    UCHIJA  inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJA  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJA  journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJA  LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    UCHIJA  MagicBees{1.7.10-2.3.5} [Magic Bees](magicbees-1.7.10-2.3.5.jar) 
    UCHIJA  MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UCHIJA  MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJA  Morpheus{1.7.10-1.6.10} [Morpheus](Morpheus-1.7.10-1.6.10.jar) 
    UCHIJA  neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCHIJA  NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCHIJA  notenoughkeys{@MOD_VERSION@} [NotEnoughKEys](NotEnoughKeys-1.7.10-1.0.0b30.jar) 
    UCHIJA  numina{0.4.0.119} [Numina](Numina-0.4.0.119.jar) 
    UCHIJA  OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJA  OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHIJA  RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJA  rftools{3.35} [RFTools](rftools-3.35.jar) 
    UCHIJA  Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar) 
    UCHIJA  Schematica{1.7.6.128} [Schematica](Schematica-1.7.10-1.7.6.128-universal.jar) 
    UCHIJA  simplyjetpacks{1.5.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.1.jar) 
    UCHIJA  ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJA  VeinMiner{0.27.1_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UCHIJA  VeinMinerModSupport{0.27.1_build.unknown} [Mod Support](VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UCHIJA  denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon (TM) R9 200 Series'
    OpenModsLib class transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    NetherOres: -[1.7.10]2.3.0-12
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon (TM) R9 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by ckaraviotis** [comment]
Pretty sure it's client side Numina. It'll be removed in the next version. Same problem as #1
